services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_BLOG_TITLE
      - WP_USER1_NAME
      - WP_USER1_EMAIL
      - WP_USER1_PASSWORD
      - WP_USER2_NAME
      - WP_USER2_EMAIL
      - WP_USER2_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]

networks:
  inception:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
