services:
  mariadb:
    build: requirements/mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
  wordpress:
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception:

volumes:
  database:
  wordpress:
