services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      network: host
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      network: host
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_BLOG_TITLE
      - WP_USER1_NAME
      - WP_USER1_EMAIL
      - WP_USER1_PASSWORD
      - WP_USER2_NAME
      - WP_USER2_EMAIL
      - WP_USER2_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      network: host
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10

networks:
  inception:

volumes:
  database:
    driver: local
    # driver_opts:
    #   type: none
    #   device: ${HOME}/data/database
    #   o: bind
  wordpress:
    driver: local
    # driver_opts:
    #   type: none
    #   device: ${HOME}/data/wordpress
    #   o: bind
