services:
  mariadb:
    build: requirements/mariadb
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    restart: always
  wordpress:
    build: requirements/wordpress
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_BLOG_TITLE
      - WP_USER1_NAME
      - WP_USER1_EMAIL
      - WP_USER1_PASSWORD
      - WP_USER2_NAME
      - WP_USER2_EMAIL
      - WP_USER2_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      - mariadb
    restart: always
  nginx:
    build: requirements/nginx
    hostname: login.42.fr
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      - wordpress
    restart: always

networks:
  inception:

volumes:
  database:
  wordpress:
