services:
  #
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      network: host
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      network: host
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DOMAIN_NAME
      - WP_BLOG_TITLE
      - WP_USER1_NAME
      - WP_USER1_EMAIL
      - WP_USER1_PASSWORD
      - WP_USER2_NAME
      - WP_USER2_EMAIL
      - WP_USER2_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      network: host
    environment:
      - DOMAIN_NAME
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      network: host
    networks:
      - inception
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  vsftpd:
    container_name: vsftpd
    build:
      context: ./requirements/bonus/vsftpd
      network: host
    environment:
      - FTP_USER
      - FTP_PASSWORD
    ports:
      - "20:20"
      - "21:21"
      - "60000-60100:60000-60100"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_started
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  website:
    container_name: website
    build:
      context: ./requirements/bonus/website
      network: host
    environment:
      - DOMAIN_NAME
    networks:
      - inception
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      network: host
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always
  #
  samba:
    container_name: samba
    build:
      context: ./requirements/bonus/samba
      network: host
    ports:
      - "445:445"
    networks:
      - inception
    volumes:
      - share:/share
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      timeout: 20s
      retries: 10
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  share:
    name: share
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/share
      o: bind
