FROM debian:bullseye

RUN apt update && \
    apt install -y python3 python3-pip && \
    apt install -y iproute2

RUN pip3 install --upgrade pip && \
	pip3 install uvicorn starlette

COPY ./html /var/www/html
COPY ./app /app

COPY ./tools/ /usr/local/bin/
RUN chmod +x /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /app

ENTRYPOINT ["entrypoint.sh"]
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]
