FROM debian:bullseye

RUN apt update && \
    apt install -y samba && \
    apt install -y iproute2

RUN mkdir -p /share && \
    chown -R nobody:nogroup /share && \
    chmod -R 0777 /share

COPY ./conf/smb.conf /etc/samba/smb.conf

COPY ./tools/ /usr/local/bin/
RUN chmod +x /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD ["smbd", "-i", "-F"]
